name: Build and Push Golang Docker Image

on:
  # Trigger only when a tag that starts with a digit is pushed (e.g. 1.0.0)
  push:
    tags:
      - '[0-9]*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: PLAYGROUND

    steps:
      # 1. Check out the repository.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. (Optional) Set up Go if you need to run tests or build your binary.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      # 3. Extract Docker metadata. This action reads the Git tag (e.g. "1.0.0")
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/example-app
          tags: |
            type=semver,pattern={{version}}

      # 4. Log in to Docker Hub. Ensure your Docker Hub credentials are stored as secrets.
      - name: Log in to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Build and push the Docker image.
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: steps.docker_login.outcome == 'success'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
